<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Switcher_Close_Icon</name>
   <tag></tag>
   <elementGuidId>35611a8c-cd84-469e-836c-c43ea4825256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='init']/div/span/div[2]/div/div[2]/div/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style__closeIcon___3lhQH col-lg-2 col-md-2 col-sm-2 col-xs-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;init&quot;)/div[@class=&quot;style__appPanelContainer___O-qIV&quot;]/span[@class=&quot;style__panelContainer___1K3ut&quot;]/div[@class=&quot;style__SwitchPanelContent___3sVyM col-lg-2 col-md-2 col-sm-2 col-xs-3&quot;]/div[@class=&quot;style__switchShape___t4H_o&quot;]/div[@class=&quot;style__BackgroundStyled___Y4qbY&quot;]/div[@class=&quot;style__sidebar___-QoH_&quot;]/span[1]/div[@class=&quot;style__logoContainer___2LOiP row&quot;]/div[@class=&quot;style__closeIcon___3lhQH col-lg-2 col-md-2 col-sm-2 col-xs-2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='init']/div/span/div[2]/div/div[2]/div/span/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toyota'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA'])[1]/following::div[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Visited Today'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
