<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_createdByanonymousUsercreatedDate2020-_c3c7b9</name>
   <tag></tag>
   <elementGuidId>510c0245-2dbb-4f21-b310-886a08c9f5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[{&quot;createdBy&quot;:&quot;anonymousUser&quot;,&quot;createdDate&quot;:&quot;2020-01-29T08:31:13Z&quot;,&quot;lastModifiedBy&quot;:&quot;anonymousUser&quot;,&quot;lastModifiedDate&quot;:&quot;2020-02-11T15:20:39Z&quot;,&quot;dataSourceId&quot;:4,&quot;dataSourceUid&quot;:&quot;vPARfmrJDA&quot;,&quot;name&quot;:&quot;RepairOrders&quot;,&quot;description&quot;:&quot;This table contains consumer data obtained via repair orders placed by the consumers.&quot;,&quot;accountId&quot;:&quot;1&quot;,&quot;status&quot;:&quot;ACTIVE&quot;,&quot;count&quot;:11,&quot;version&quot;:0,&quot;dataSourceMetaData&quot;:[{&quot;createdBy&quot;:&quot;anonymousUser&quot;,&quot;createdDate&quot;:&quot;2020-02-05T05:55:46Z&quot;,&quot;lastModifiedBy&quot;:&quot;anonymousUser&quot;,&quot;lastModifiedDate&quot;:&quot;2020-02-05T05:57:12Z&quot;,&quot;dataSourceMetaDataId&quot;:1,&quot;dataSourceMetaDataUid&quot;:&quot;-dB1fpO__A&quot;,&quot;name&quot;:&quot;Repair Order Number&quot;,&quot;description&quot;:&quot;Repair order number&quot;,&quot;type&quot;:&quot;Long&quot;,&quot;length&quot;:50,&quot;decimalLength&quot;:0,&quot;status&quot;:&quot;ACTIVE&quot;,&quot;version&quot;:0},{&quot;createdBy&quot;:&quot;anonymousUser&quot;,&quot;createdDate&quot;:&quot;2020-02-05T05:55:54Z&quot;,&quot;lastModifiedBy&quot;:&quot;anonymousUser&quot;,&quot;lastModifiedDate&quot;:&quot;2020-02-05T05:57:12Z&quot;,&quot;dataSourceMetaDataId&quot;:2,&quot;dataSourceMetaDataUid&quot;:&quot;2FNNGUOdPA&quot;,&quot;name&quot;:&quot;RO Date&quot;,&quot;description&quot;:&quot;Repair order date&quot;,&quot;type&quot;:&quot;String&quot;,&quot;length&quot;:50,&quot;decimalLength&quot;:0,&quot;status&quot;:&quot;ACTIVE&quot;,&quot;version&quot;:0},{&quot;createdBy&quot;:&quot;anonymousUser&quot;,&quot;createdDate&quot;:&quot;2020-02-05T05:56:01Z&quot;,&quot;lastModifiedBy&quot;:&quot;anonymousUser&quot;,&quot;lastModifiedDate&quot;:&quot;2020-02-05T05:57:12Z&quot;,&quot;dataSourceMetaDataId&quot;:3,&quot;dataSourceMetaDataUid&quot;:&quot;wfhEdDCy6A&quot;,&quot;name&quot;:&quot;Repair Type&quot;,&quot;description&quot;:&quot;Repair order type&quot;,&quot;type&quot;:&quot;String&quot;,&quot;length&quot;:50,&quot;decimalLength&quot;:0,&quot;status&quot;:&quot;ACTIVE&quot;,&quot;version&quot;:0}]}]/html[1]/body[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
