<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_typehttpswwwjhipstertechproblemproblem_2db3c2</name>
   <tag></tag>
   <elementGuidId>9d776602-f4b7-42c9-b9b0-94c3b0dfb604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;https://www.jhipster.tech/problem/problem-with-message&quot;,&quot;title&quot;:&quot;Method Not Allowed&quot;,&quot;status&quot;:405,&quot;detail&quot;:&quot;Request method 'GET' not supported&quot;,&quot;path&quot;:&quot;/services/configuration/api/authenticate&quot;,&quot;message&quot;:&quot;error.http.405&quot;}/html[1]/body[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
