<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ampimage</name>
   <tag></tag>
   <elementGuidId>805a7a0e-6ebe-4a45-bbc3-fc960850fb4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@alt='AMP']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='http://dqfn4clx0bazt.cloudfront.net/init/380bfcf899971f7d559215551dc6c715.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@alt='AMP']</value>
   </webElementProperties>
</WebElementEntity>
